using UADetector.Models;
using UADetector.Regexes.Models;
using UADetector.Utils;

namespace UADetector.Parsers;

public class OperatingSystemParser
{
    private const string ResourceName = "Regexes.operating_systems.yml";

    private static readonly IEnumerable<OperatingSystemRegex> Regexes =
        ParserExtensions.LoadRegexes<OperatingSystemRegex>(ResourceName);

    private static readonly FrozenBiDictionary<string, OsShortName> OperatingSystems =
        new(new Dictionary<OsShortName, string>
        {
            { OsShortName.AIX, "AIX" },
            { OsShortName.AND, "Android" },
            { OsShortName.ADR, "Android TV" },
            { OsShortName.ALP, "Alpine Linux" },
            { OsShortName.AMZ, "Amazon Linux" },
            { OsShortName.AMG, "AmigaOS" },
            { OsShortName.ARM, "Armadillo OS" },
            { OsShortName.ARO, "AROS" },
            { OsShortName.ATV, "tvOS" },
            { OsShortName.ARL, "Arch Linux" },
            { OsShortName.AOS, "AOSC OS" },
            { OsShortName.ASP, "ASPLinux" },
            { OsShortName.AZU, "Azure Linux" },
            { OsShortName.BTR, "BackTrack" },
            { OsShortName.SBA, "Bada" },
            { OsShortName.BYI, "Baidu Yi" },
            { OsShortName.BEO, "BeOS" },
            { OsShortName.BLB, "BlackBerry OS" },
            { OsShortName.QNX, "BlackBerry Tablet OS" },
            { OsShortName.PAN, "blackPanther OS" },
            { OsShortName.BOS, "Bliss OS" },
            { OsShortName.BMP, "Brew" },
            { OsShortName.BSN, "BrightSignOS" },
            { OsShortName.CAI, "Caixa Mágica" },
            { OsShortName.CES, "CentOS" },
            { OsShortName.CST, "CentOS Stream" },
            { OsShortName.CLO, "Clear Linux OS" },
            { OsShortName.CLR, "ClearOS Mobile" },
            { OsShortName.COS, "Chrome OS" },
            { OsShortName.CRS, "Chromium OS" },
            { OsShortName.CHN, "China OS" },
            { OsShortName.COL, "Coolita OS" },
            { OsShortName.CYN, "CyanogenMod" },
            { OsShortName.DEB, "Debian" },
            { OsShortName.DEE, "Deepin" },
            { OsShortName.DFB, "DragonFly" },
            { OsShortName.DVK, "DVKBuntu" },
            { OsShortName.ELE, "ElectroBSD" },
            { OsShortName.EUL, "EulerOS" },
            { OsShortName.FED, "Fedora" },
            { OsShortName.FEN, "Fenix" },
            { OsShortName.FOS, "Firefox OS" },
            { OsShortName.FIR, "Fire OS" },
            { OsShortName.FOR, "Foresight Linux" },
            { OsShortName.FRE, "Freebox" },
            { OsShortName.BSD, "FreeBSD" },
            { OsShortName.FRI, "FRITZ!OS" },
            { OsShortName.FYD, "FydeOS" },
            { OsShortName.FUC, "Fuchsia" },
            { OsShortName.GNT, "Gentoo" },
            { OsShortName.GNX, "GENIX" },
            { OsShortName.GEO, "GEOS" },
            { OsShortName.GNS, "gNewSense" },
            { OsShortName.GRI, "GridOS" },
            { OsShortName.GTV, "Google TV" },
            { OsShortName.HPX, "HP-UX" },
            { OsShortName.HAI, "Haiku OS" },
            { OsShortName.IPA, "iPadOS" },
            { OsShortName.HAR, "HarmonyOS" },
            { OsShortName.HAS, "HasCodingOS" },
            { OsShortName.HEL, "HELIX OS" },
            { OsShortName.IRI, "IRIX" },
            { OsShortName.INF, "Inferno" },
            { OsShortName.JME, "Java ME" },
            { OsShortName.JOL, "Joli OS" },
            { OsShortName.KOS, "KaiOS" },
            { OsShortName.KAL, "Kali" },
            { OsShortName.KAN, "Kanotix" },
            { OsShortName.KIN, "KIN OS" },
            { OsShortName.KNO, "Knoppix" },
            { OsShortName.KTV, "KreaTV" },
            { OsShortName.KBT, "Kubuntu" },
            { OsShortName.LIN, "GNU/Linux" },
            { OsShortName.LEA, "LeafOS" },
            { OsShortName.LND, "LindowsOS" },
            { OsShortName.LNS, "Linspire" },
            { OsShortName.LEN, "Lineage OS" },
            { OsShortName.LIR, "Liri OS" },
            { OsShortName.LOO, "Loongnix" },
            { OsShortName.LBT, "Lubuntu" },
            { OsShortName.LOS, "Lumin OS" },
            { OsShortName.LUN, "LuneOS" },
            { OsShortName.VLN, "VectorLinux" },
            { OsShortName.MAC, "Mac" },
            { OsShortName.MAE, "Maemo" },
            { OsShortName.MAG, "Mageia" },
            { OsShortName.MDR, "Mandriva" },
            { OsShortName.SMG, "MeeGo" },
            { OsShortName.MET, "Meta Horizon" },
            { OsShortName.MCD, "MocorDroid" },
            { OsShortName.MON, "moonOS" },
            { OsShortName.EZX, "Motorola EZX" },
            { OsShortName.MIN, "Mint" },
            { OsShortName.MLD, "MildWild" },
            { OsShortName.MOR, "MorphOS" },
            { OsShortName.NBS, "NetBSD" },
            { OsShortName.MTK, "MTK / Nucleus" },
            { OsShortName.MRE, "MRE" },
            { OsShortName.NXT, "NeXTSTEP" },
            { OsShortName.NWS, "NEWS-OS" },
            { OsShortName.WII, "Nintendo" },
            { OsShortName.NDS, "Nintendo Mobile" },
            { OsShortName.NOV, "Nova" },
            { OsShortName.OS2, "OS/2" },
            { OsShortName.T64, "OSF1" },
            { OsShortName.OBS, "OpenBSD" },
            { OsShortName.OVS, "OpenVMS" },
            { OsShortName.OVZ, "OpenVZ" },
            { OsShortName.OWR, "OpenWrt" },
            { OsShortName.OTV, "Opera TV" },
            { OsShortName.ORA, "Oracle Linux" },
            { OsShortName.ORD, "Ordissimo" },
            { OsShortName.PAR, "Pardus" },
            { OsShortName.PCL, "PCLinuxOS" },
            { OsShortName.PIC, "PICO OS" },
            { OsShortName.PLA, "Plasma Mobile" },
            { OsShortName.PSP, "PlayStation Portable" },
            { OsShortName.PS3, "PlayStation" },
            { OsShortName.PVE, "Proxmox VE" },
            { OsShortName.PUF, "Puffin OS" },
            { OsShortName.PUR, "PureOS" },
            { OsShortName.QTP, "Qtopia" },
            { OsShortName.PIO, "Raspberry Pi OS" },
            { OsShortName.RAS, "Raspbian" },
            { OsShortName.RHT, "Red Hat" },
            { OsShortName.RST, "Red Star" },
            { OsShortName.RED, "RedOS" },
            { OsShortName.REV, "Revenge OS" },
            { OsShortName.RIS, "risingOS" },
            { OsShortName.ROS, "RISC OS" },
            { OsShortName.ROC, "Rocky Linux" },
            { OsShortName.ROK, "Roku OS" },
            { OsShortName.RSO, "Rosa" },
            { OsShortName.ROU, "RouterOS" },
            { OsShortName.REM, "Remix OS" },
            { OsShortName.RRS, "Resurrection Remix OS" },
            { OsShortName.REX, "REX" },
            { OsShortName.RZD, "RazoDroiD" },
            { OsShortName.RXT, "RTOS & Next" },
            { OsShortName.SAB, "Sabayon" },
            { OsShortName.SSE, "SUSE" },
            { OsShortName.SAF, "Sailfish OS" },
            { OsShortName.SCI, "Scientific Linux" },
            { OsShortName.SEE, "SeewoOS" },
            { OsShortName.SER, "SerenityOS" },
            { OsShortName.SIR, "Sirin OS" },
            { OsShortName.SLW, "Slackware" },
            { OsShortName.SOS, "Solaris" },
            { OsShortName.SBL, "Star-Blade OS" },
            { OsShortName.SYL, "Syllable" },
            { OsShortName.SYM, "Symbian" },
            { OsShortName.SYS, "Symbian OS" },
            { OsShortName.S40, "Symbian OS Series 40" },
            { OsShortName.S60, "Symbian OS Series 60" },
            { OsShortName.SY3, "Symbian^3" },
            { OsShortName.TEN, "TencentOS" },
            { OsShortName.TDX, "ThreadX" },
            { OsShortName.TIZ, "Tizen" },
            { OsShortName.TIV, "TiVo OS" },
            { OsShortName.TOS, "TmaxOS" },
            { OsShortName.TUR, "Turbolinux" },
            { OsShortName.UBT, "Ubuntu" },
            { OsShortName.ULT, "ULTRIX" },
            { OsShortName.UOS, "UOS" },
            { OsShortName.VID, "VIDAA" },
            { OsShortName.VIZ, "ViziOS" },
            { OsShortName.WAS, "watchOS" },
            { OsShortName.WER, "Wear OS" },
            { OsShortName.WTV, "WebTV" },
            { OsShortName.WHS, "Whale OS" },
            { OsShortName.WIN, "Windows" },
            { OsShortName.WCE, "Windows CE" },
            { OsShortName.WIO, "Windows IoT" },
            { OsShortName.WMO, "Windows Mobile" },
            { OsShortName.WPH, "Windows Phone" },
            { OsShortName.WRT, "Windows RT" },
            { OsShortName.WPO, "WoPhone" },
            { OsShortName.XBX, "Xbox" },
            { OsShortName.XBT, "Xubuntu" },
            { OsShortName.YNS, "YunOS" },
            { OsShortName.ZEN, "Zenwalk" },
            { OsShortName.ZOR, "ZorinOS" },
            { OsShortName.IOS, "iOS" },
            { OsShortName.POS, "palmOS" },
            { OsShortName.WEB, "Webian" },
            { OsShortName.WOS, "webOS" },
        }.ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase));
}
