using Shouldly;
using UaDetector.Abstractions.Enums;

namespace UaDetector.Abstractions.Tests.Enums;

public class OsCodeTests
{
    [Test]
    public void OsCode_ValuesShouldBeSequential()
    {
        var values = Enum.GetValues<OsCode>().Cast<int>().ToList();

        for (int i = 0; i < values.Count; i++)
        {
            values[i].ShouldBe(i + 1);
        }
    }

    [Test]
    public void OsCode_HasExpectedValues()
    {
        var expectedValues = new Dictionary<OsCode, int>
        {
            { OsCode.Aix, 1 },
            { OsCode.Android, 2 },
            { OsCode.AndroidTv, 3 },
            { OsCode.AlpineLinux, 4 },
            { OsCode.AmazonLinux, 5 },
            { OsCode.AmigaOs, 6 },
            { OsCode.ArmadilloOs, 7 },
            { OsCode.Aros, 8 },
            { OsCode.TvOs, 9 },
            { OsCode.ArchLinux, 10 },
            { OsCode.AoscOs, 11 },
            { OsCode.AspLinux, 12 },
            { OsCode.AzureLinux, 13 },
            { OsCode.BackTrack, 14 },
            { OsCode.Bada, 15 },
            { OsCode.BaiduYi, 16 },
            { OsCode.BeOs, 17 },
            { OsCode.BlackBerryOs, 18 },
            { OsCode.BlackBerryTabletOs, 19 },
            { OsCode.BlackPantherOs, 20 },
            { OsCode.BlissOs, 21 },
            { OsCode.Brew, 22 },
            { OsCode.BrightSignOs, 23 },
            { OsCode.CaixaMagica, 24 },
            { OsCode.CentOs, 25 },
            { OsCode.CentOsStream, 26 },
            { OsCode.ClearLinuxOs, 27 },
            { OsCode.ClearOsMobile, 28 },
            { OsCode.ChromeOs, 29 },
            { OsCode.ChromiumOs, 30 },
            { OsCode.ChinaOs, 31 },
            { OsCode.CoolitaOs, 32 },
            { OsCode.CyanogenMod, 33 },
            { OsCode.Debian, 34 },
            { OsCode.Deepin, 35 },
            { OsCode.DragonFly, 36 },
            { OsCode.DvkBuntu, 37 },
            { OsCode.ElectroBsd, 38 },
            { OsCode.EulerOs, 39 },
            { OsCode.Fedora, 40 },
            { OsCode.Fenix, 41 },
            { OsCode.FirefoxOs, 42 },
            { OsCode.FireOs, 43 },
            { OsCode.ForesightLinux, 44 },
            { OsCode.Freebox, 45 },
            { OsCode.FreeBsd, 46 },
            { OsCode.FritzOs, 47 },
            { OsCode.FydeOs, 48 },
            { OsCode.Fuchsia, 49 },
            { OsCode.Gentoo, 50 },
            { OsCode.Genix, 51 },
            { OsCode.Geos, 52 },
            { OsCode.GNewSense, 53 },
            { OsCode.GridOs, 54 },
            { OsCode.GoogleTv, 55 },
            { OsCode.HpUx, 56 },
            { OsCode.HaikuOs, 57 },
            { OsCode.IPadOs, 58 },
            { OsCode.HarmonyOs, 59 },
            { OsCode.HasCodingOs, 60 },
            { OsCode.HelixOs, 61 },
            { OsCode.Irix, 62 },
            { OsCode.Inferno, 63 },
            { OsCode.JavaMe, 64 },
            { OsCode.JoliOs, 65 },
            { OsCode.KaiOs, 66 },
            { OsCode.Kali, 67 },
            { OsCode.Kanotix, 68 },
            { OsCode.KinOs, 69 },
            { OsCode.Knoppix, 70 },
            { OsCode.KreaTv, 71 },
            { OsCode.Kubuntu, 72 },
            { OsCode.GnuLinux, 73 },
            { OsCode.LeafOs, 74 },
            { OsCode.LindowsOs, 75 },
            { OsCode.Linspire, 76 },
            { OsCode.LineageOs, 77 },
            { OsCode.LiriOs, 78 },
            { OsCode.Loongnix, 79 },
            { OsCode.Lubuntu, 80 },
            { OsCode.LuminOs, 81 },
            { OsCode.LuneOs, 82 },
            { OsCode.VectorLinux, 83 },
            { OsCode.Mac, 84 },
            { OsCode.Maemo, 85 },
            { OsCode.Mageia, 86 },
            { OsCode.Mandriva, 87 },
            { OsCode.MeeGo, 88 },
            { OsCode.MetaHorizon, 89 },
            { OsCode.MocorDroid, 90 },
            { OsCode.MoonOs, 91 },
            { OsCode.MotorolaEzx, 92 },
            { OsCode.Mint, 93 },
            { OsCode.MildWild, 94 },
            { OsCode.MorphOs, 95 },
            { OsCode.NetBsd, 96 },
            { OsCode.MtkNucleus, 97 },
            { OsCode.Mre, 98 },
            { OsCode.NextStep, 99 },
            { OsCode.NewsOs, 100 },
            { OsCode.Nintendo, 101 },
            { OsCode.NintendoMobile, 102 },
            { OsCode.Nova, 103 },
            { OsCode.Os2, 104 },
            { OsCode.Osf1, 105 },
            { OsCode.OpenBsd, 106 },
            { OsCode.OpenVms, 107 },
            { OsCode.OpenVz, 108 },
            { OsCode.OpenWrt, 109 },
            { OsCode.OperaTv, 110 },
            { OsCode.OracleLinux, 111 },
            { OsCode.Ordissimo, 112 },
            { OsCode.Pardus, 113 },
            { OsCode.PcLinuxOs, 114 },
            { OsCode.PicoOs, 115 },
            { OsCode.PlasmaMobile, 116 },
            { OsCode.PlayStationPortable, 117 },
            { OsCode.PlayStation, 118 },
            { OsCode.ProxmoxVe, 119 },
            { OsCode.PuffinOs, 120 },
            { OsCode.PureOs, 121 },
            { OsCode.Qtopia, 122 },
            { OsCode.RaspberryPiOs, 123 },
            { OsCode.Raspbian, 124 },
            { OsCode.RedHat, 125 },
            { OsCode.RedStar, 126 },
            { OsCode.RedOs, 127 },
            { OsCode.RevengeOs, 128 },
            { OsCode.RisingOs, 129 },
            { OsCode.RiscOs, 130 },
            { OsCode.RockyLinux, 131 },
            { OsCode.RokuOs, 132 },
            { OsCode.Rosa, 133 },
            { OsCode.RouterOs, 134 },
            { OsCode.RemixOs, 135 },
            { OsCode.ResurrectionRemixOs, 136 },
            { OsCode.Rex, 137 },
            { OsCode.RazoDroid, 138 },
            { OsCode.RtosAndNext, 139 },
            { OsCode.Sabayon, 140 },
            { OsCode.Suse, 141 },
            { OsCode.SailfishOs, 142 },
            { OsCode.ScientificLinux, 143 },
            { OsCode.SeewoOs, 144 },
            { OsCode.SerenityOs, 145 },
            { OsCode.SirinOs, 146 },
            { OsCode.Slackware, 147 },
            { OsCode.Solaris, 148 },
            { OsCode.StarBladeOs, 149 },
            { OsCode.Syllable, 150 },
            { OsCode.Symbian, 151 },
            { OsCode.SymbianOs, 152 },
            { OsCode.SymbianOsSeries40, 153 },
            { OsCode.SymbianOsSeries60, 154 },
            { OsCode.Symbian3, 155 },
            { OsCode.TencentOs, 156 },
            { OsCode.ThreadX, 157 },
            { OsCode.Tizen, 158 },
            { OsCode.TiVoOs, 159 },
            { OsCode.TmaxOs, 160 },
            { OsCode.Turbolinux, 161 },
            { OsCode.Ubuntu, 162 },
            { OsCode.Ultrix, 163 },
            { OsCode.Uos, 164 },
            { OsCode.Vidaa, 165 },
            { OsCode.ViziOs, 166 },
            { OsCode.WatchOs, 167 },
            { OsCode.WearOs, 168 },
            { OsCode.WebTv, 169 },
            { OsCode.WhaleOs, 170 },
            { OsCode.Windows, 171 },
            { OsCode.WindowsCe, 172 },
            { OsCode.WindowsIoT, 173 },
            { OsCode.WindowsMobile, 174 },
            { OsCode.WindowsPhone, 175 },
            { OsCode.WindowsRt, 176 },
            { OsCode.WoPhone, 177 },
            { OsCode.Xbox, 178 },
            { OsCode.Xubuntu, 179 },
            { OsCode.YunOs, 180 },
            { OsCode.Zenwalk, 181 },
            { OsCode.ZorinOs, 182 },
            { OsCode.IOs, 183 },
            { OsCode.PalmOs, 184 },
            { OsCode.Webian, 185 },
            { OsCode.WebOs, 186 },
            { OsCode.KolibriOs, 187 },
            { OsCode.OpenHarmony, 188 },
            { OsCode.SmartisanOs, 189 },
            { OsCode.TitanOs, 190 },
            { OsCode.ArcaOs, 191 },
            { OsCode.Contiki, 192 },
            { OsCode.ElementaryOs, 193 },
            { OsCode.GhostBsd, 194 },
            { OsCode.Linpus, 195 },
            { OsCode.Minix, 196 },
            { OsCode.MocorOs, 197 },
            { OsCode.Plan9, 198 },
            { OsCode.Bsd, 199 },
            { OsCode.OpenSuse, 200 },
            { OsCode.Orsay, 201 },
            { OsCode.NuttX, 202 },
        };

        expectedValues.Count.ShouldBe(Enum.GetValues<OsCode>().Length);

        foreach (var osCode in Enum.GetValues<OsCode>())
        {
            ((int)osCode).ShouldBe(expectedValues[osCode]);
        }
    }
}
